src/Entity/Artist.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ArtistRepository")
 */
class Artist
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotNull
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\NotNull
     */
    private $twitter_handle;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTwitterHandle(): ?string
    {
        return $this->twitter_handle;
    }

    public function setTwitterHandle(?string $twitter_handle): self
    {
        $this->twitter_handle = $twitter_handle;

        return $this;
    }
    public function __toString()
    {
        return $this->name;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Music Collection{% endblock %}</title>
        <!-- Meta tags Obrigatórias -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

        {% block stylesheets %}{% endblock %}
    </head>
    <body>
        {% if is_granted('ROLE_USER') %}
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Music Collection</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="/artist">Artist</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/album">Album</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    </ul>

                </div>
            </nav>
        {% endif %}

        <div class="container">
            <div class="row">
                <div class="col-12">
                    {# read and display just one flash message type #}
                    {% for message in app.flashes('notice') %}
                        <p>
                        <div class="alert alert-success" role="alert">
                            {{ message }}
                        </div>
                        </p>
                    {% endfor %}
                    {% block body %}{% endblock %}
                </div>
            </div>
        </div>
        {% block javascripts %}{% endblock %}
    </body>
</html>

templates/create.html.twig
{% extends 'base.html.twig' %}
{% block body%}
    <h1>{{title}}</h1>
    {{form(form)}}
{% endblock %}

templates/list_album.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <br>
<div class="card">
  <div class="card-header">
    <div class="row">
        <div class="col-10">
            <h1>{{title}}</h1>
        </div>
        <div class="col-2">
            <a class="btn btn-primary" href="/album_create">Create Album</a>
        </div>
    </div>    
</div>
  <div class="card-body">
    {% for album in albums %}
        {% if loop.first %}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Artist</th>
                        <th scope="col">Year</th>
                        <th scope="col">Edit</th>
                    </tr>
                </thead>
                <tbody>
        {% endif %}
        <tr>
            <td scope="row">{{album.id}}</td>
            <td>{{album.name}}</td>
            <td>{{album.artist}}</td>
            <td>{{album.year}}</td>
            <td>
                <a class="btn btn-primary" href="/album_update/{{album.id}}">Edit</a>
            </td>
        </tr>
        {% if loop.last %}    
            </tbody>
        </table>
        {% endif %}
    {% else %}
        <div class="row">
            <div class="col-12 alert alert-dark" role="alert">Records not found</div>
        </div>
    {% endfor %}
</div>
  <div class="card-footer">
    {% if maxPages > 1 %}
        <nav>
            <ul class="pagination justify-content-center">
                <li {{ thisPage == 1 ? 'class="disabled":class="page-item"' }}>
                    <a class="page-link" href="/album/{{thisPage-1 < 1 ? 1 : thisPage-1}}">«</a>
                </li>
                {% for i in 1..maxPages %}
                <li {{ thisPage == i ? 'class="active":class="page-item"' }}>
                <a  class="page-link" href="/album/{{i}}">{{ i }}</a>
                </li>
                {% endfor %}

                {# `»` arrow #}
                <li {{ thisPage == maxPages ? 'class="disabled":class="page-item"' }}>
                    <a  class="page-link" href="/album/{{ thisPage+1 <= maxPages ? thisPage+1 : thisPage}}">»</a>
                </li>
            </ul>
        </dnav>
    {% endif %}
    </div>
</div>
{% endblock %}

templates/list_artist.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<br>
<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-10">
                <h1>{{title}}</h1>
            </div>
            <div class="col-2">
                <a class="btn btn-primary" href="/artist_create">Create Artist</a>
            </div>
        </div>    
    </div>
    <div class="card-body">
        {% for artist in artists %}
            {% if loop.first %}
                <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Twitter Handle</th>
                        <th scope="col">Edit</th>
                    </tr>
                </thead>
                <tbody>
            {% endif %}
            <tr>
                <td scope="row">{{artist.id}}</td>
                <td>{{artist.name}}</td>
                <td>{{artist.twitterHandle}}</td>
                <td><a class="btn btn-primary" href="/artist_update/{{artist.id}}">Edit</a></td>
            </tr>
            {% if loop.last %} 
                    </tbody>      
                </table>
            {% endif %}
        {% else %}
            <div class="row">
                <div class="col-12 alert alert-dark" role="alert">Records not found</div>
            </div>
        {% endfor %}
    </div>
    <div class="card-footer">   
        {% if maxPages > 1 %}
            <nav>
                <ul class="pagination justify-content-center">
                    <li {{ thisPage == 1 ? 'class="disabled":class="page-item"' }}>
                        <a class="page-link" href="/artist/{{thisPage-1 < 1 ? 1 : thisPage-1}}">«</a>
                    </li>
                    {% for i in 1..maxPages %}
                    <li {{ thisPage == i ? 'class="active":class="page-item"' }}>
                    <a  class="page-link" href="/artist/{{i}}">{{ i }}</a>
                    </li>
                    {% endfor %}

                    {# `»` arrow #}
                    <li {{ thisPage == maxPages ? 'class="disabled":class="page-item"' }}>
                        <a  class="page-link" href="/artist/{{ thisPage+1 <= maxPages ? thisPage+1 : thisPage}}">»</a>
                    </li>
                </ul>
            </nav>
        {% endif %}
    </div>
</div>
{% endblock %}